name: Publish to NuGet

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true
  DOTNET_NOLOGO: true

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Check Secret
      run: |
        if [ -z "${{ secrets.NUGET_API_KEY }}" ]; then
          echo "❌ NUGET_API_KEY is empty"
          exit 1
        else
          echo "✅ NUGET_API_KEY is set"
        fi
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Pack
      run: dotnet pack --configuration Release
    
    - name: Push to NuGet
      run: dotnet nuget push "**/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json --skip-duplicate
